meta:
  version: efiqa_cp
  description: EFIQA-CP with dense CNN adapter and pixel-level nnPU on MSHF.

traindata:
  key: SLDataset
  params:
    feat_dir:
      - /home/penway/Projects/FIQA/IQX/data/MSHF/emb_dino_1024
    seg_dir:
      - /home/penway/Projects/FIQA/IQX/data/MSHF/seg/vuad/patch

trainer:
  batch_size: 16
  epochs: 100
  device: cuda
  seed: 504
  num_workers: 8
  log_interval: 200
  ckpt_interval: 1

optim:
  key: adamw
  params:
    lr: 0.001

model:
  key: sa_cnn
  params:
    in_channels: 1024
    mid_channels: 512
    mlp_ratio: 1

loss:
  key: nnpu
  params:
    pi: 0.05
    beta: 0.0
    pos_weight: 1

hydra:
  job:
    chdir: false
  run:
    dir: ./experiments/badish/efiqa_cp/${now:%Y%m%d_%H%M%S}
