meta:
  version: efiqa
  description: Original EFIQA linear adapter with supervised BCE on MSHF.

traindata:
  key: PatchDataset
  params:
    patch_dataset_path: /home/penway/Projects/FIQA/IQX/data/MSHF/patch/mshf_patch_dataset.npz
    balance: false

trainer:
  batch_size: 4096
  epochs: 100
  device: cuda
  seed: 504
  num_workers: 8
  log_interval: 200
  ckpt_interval: 20

optim:
  key: adamw
  params:
    lr: 0.001

model:
  key: sc_linear
  params:
    input_dim: 1024
    output_dim: 1

loss:
  key: bce_pos_weight
  params:
    pos_weight: 9.58

hydra:
  job:
    chdir: false
  run:
    dir: ./experiments/badish/efiqa/${now:%Y%m%d_%H%M%S}
